#pragma once

#define EE_HANDS
#define VIAL_KEYBOARD_UID {0x19, 0x6c, 0x83, 0xc5, 0x08, 0x26, 0xde, 0x1a}
#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_X_RIGHT
#define POINTING_DEVICE_INVERT_Y_RIGHT